version: "3.7"

services:
  clientelo-db:
    image: mysql:8.0
    ports:
      - "33006:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=clientelo
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=clientelo
    volumes:
      - ./db:/var/lib/mysql
